volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  backend:
    container_name: foodgram-backend
    build: ../backend/
    image: sergeyku87/foodgram-backend
    depends_on:
      - db
    env_file: .env-develop
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             cp -r static_backend/. /static/static/ &&
             gunicorn -b 0:8000 config.wsgi"
    volumes:
      - foodgram_static:/static
      - foodgram_media:/media

  frontend:
    container_name: foodgram-frontend
    build: ../frontend
    image: sergeyku87/foodgram-frontend
    command: cp -r /app/build/. /static_frontend/
    volumes:
      - foodgram_static:/static_frontend
  
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env-develop
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  gateway:
    container_name: foodgram-gateway
    build: ../nginx/
    image: sergeyku87/foodgram-gateway
    ports:
      - 7000:80
    depends_on:
      - backend
    restart: always
    volumes:
      - foodgram_static:/static/
      - foodgram_media:/media/
